@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Board",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1195721581 { 
   	label=SliderGame
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SliderGame1195721581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SliderGame</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   gameboard: SliderBoard [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># checkWin(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># endGame()</TD></TR>
<TR><TD ALIGN="LEFT" ># executeNextMove()</TD></TR>
<TR><TD ALIGN="LEFT" >+ runSlider()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1493690672 { 
   	label=PuzzlePiece
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   PuzzlePiece1493690672[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PuzzlePiece</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   content: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1583125093 { 
   	label=SliderBoard
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   SliderBoard1583125093[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SliderBoard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   missing_tile: int[] [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- makeSolvable()</TD></TR>
<TR><TD ALIGN="LEFT" ># populateBoard()</TD></TR>
<TR><TD ALIGN="LEFT" >+ printCurrentBoard()</TD></TR>
<TR><TD ALIGN="LEFT" >+ slide_tile(key: String)</TD></TR>
<TR><TD ALIGN="LEFT" ># swap_tiles(tile1_coordinates: int[], tile2_coordinates: int[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1901885695 { 
   	label=Player
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Player1901885695[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Player</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   customInitial: Character [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   score: float [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   turn: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ incrementScore()</TD></TR>
<TR><TD ALIGN="LEFT" >- pickInitialFromName(name: String, used: Set&lt;Character&gt;): char</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptForName(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptMultiplePlayersForNames(players: Player[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2059062913 { 
   	label=DABBoard
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DABBoard2059062913[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DABBoard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   hOwner: Player[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vOwner: Player[][] [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- boxComplete(br: int, bc: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ getValidConnections(row: int, col: int): HashMap&lt;String, int[]&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- hasHEdge(r: int, c: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- hasVEdge(r: int, c: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># invalidDimensionMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># isValidDimension(w: int, h: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeConnection(r1: int, c1: int, r2: int, c2: int, owner: Player): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ printCurrentBoard()</TD></TR>
<TR><TD ALIGN="LEFT" ># valid_position(r: int, c: int): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2144767223 { 
   	label=DABGame
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DABGame2144767223[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DABGame</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   gameboard: DABBoard [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ checkWin(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ endGame()</TD></TR>
<TR><TD ALIGN="LEFT" >+ executeNextMove()</TD></TR>
<TR><TD ALIGN="LEFT" >+ runDAB()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2211858 { 
   	label=Game
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Game2211858[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Game</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   board_height: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   board_width: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   players: Player[] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   turn_count: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># checkWin(): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># endGame()</TD></TR>
<TR><TD ALIGN="LEFT" ># executeNextMove()</TD></TR>
<TR><TD ALIGN="LEFT" ># getDesiredBoardDimensions(validator: DimensionValidator): int[]</TD></TR>
<TR><TD ALIGN="LEFT" ># initializeGame(gameType: GameType, gameboard: Board)</TD></TR>
<TR><TD ALIGN="LEFT" ># playGame(gameboard: Board)</TD></TR>
<TR><TD ALIGN="LEFT" ># quitIfRequested(input: String)</TD></TR>
<TR><TD ALIGN="LEFT" ># welcome(gameName: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2606798 { 
   	label=Tile
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Tile2606798[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Tile&lt;T extends Piece&gt;</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   piecesOnTile: ArrayList&lt;T&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addPiece(piece: T)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removePiece(piece: T)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_64356038 { 
   	label=Board
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Board64356038[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Board&lt;T extends Piece&gt;</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   board_arr: Tile&lt;T&gt;[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   height: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   positions_map: HashMap&lt;String, int[]&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >+   width: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># getInvalidPositionMessage(x: int, y: int): String</TD></TR>
<TR><TD ALIGN="LEFT" ># invalidDimensionMessage(): String</TD></TR>
<TR><TD ALIGN="LEFT" ># isValidDimension(w: int, h: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ printCurrentBoard()</TD></TR>
<TR><TD ALIGN="LEFT" >+ valid_dimension(w: int, h: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" ># valid_position(x: int, y: int): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_77109966 { 
   	label=Piece
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Piece77109966[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Piece</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_909086393 { 
   	label=ConnectionsPiece
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ConnectionsPiece909086393[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ConnectionsPiece</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   connectedPieces: HashSet&lt;ConnectionsPiece&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addConnection(piece: ConnectionsPiece)</TD></TR>
<TR><TD ALIGN="LEFT" >+ piecesAreConnected(a: ConnectionsPiece, b: ConnectionsPiece): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Board64356038 -> DABBoard2059062913[arrowhead=none, arrowtail=empty, dir=both];
Board64356038 -> SliderBoard1583125093[arrowhead=none, arrowtail=empty, dir=both];
Board64356038 -> Tile2606798[label="board_arr
[0..*]"];
DABBoard2059062913 -> Player1901885695[label="hOwner
[0..*]"];
DABBoard2059062913 -> Player1901885695[label="vOwner
[0..*]"];
DABGame2144767223 -> DABBoard2059062913[label="gameboard
[0..1]"];
Game2211858 -> DABGame2144767223[arrowhead=none, arrowtail=empty, dir=both];
Game2211858 -> SliderGame1195721581[arrowhead=none, arrowtail=empty, dir=both];
Piece77109966 -> ConnectionsPiece909086393[arrowhead=none, arrowtail=empty, dir=both];
Piece77109966 -> PuzzlePiece1493690672[arrowhead=none, arrowtail=empty, dir=both];
SliderBoard1583125093 -> Tile2606798[label="populateBoard() -> addPiece()"];
SliderGame1195721581 -> SliderBoard1583125093[label="gameboard
[0..1]"];
    
}
@enduml